# Generated by Django 3.1.1 on 2020-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email_address',
        ),
    ]
