# Generated by Django 3.1.1 on 2020-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_member_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('article_author', models.CharField(max_length=50)),
                ('article_post', models.DateField()),
                ('article_tag', models.CharField(max_length=50)),
                ('article_contents', models.CharField(max_length=10000)),
            ],
        ),
    ]
