# Generated by Django 3.1.1 on 2020-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201121_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
        migrations.AddField(
            model_name='member',
            name='interest_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
