# Generated by Django 3.1.1 on 2020-11-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
