# Generated by Django 3.1.1 on 2020-11-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201107_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_post',
            new_name='article_date',
        ),
    ]
