# Generated by Django 3.1.1 on 2020-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201107_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interest_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
